services:
  - type: web
    name: n8n
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    buildCommand: ""
    startCommand: "n8n"
    healthCheckPath: "/"
    healthCheckPort: 5678
    port: 5678
